### PR TITLE
Keyed/unkeyed boxes as structs

### PR DESCRIPTION
**Pull request by regexident**
Not sure yet, if this will actually lead to an improvement of performance.

Running the benchmark from https://github.com/MaxDesiatov/XMLCoder/pull/34 should give a better image of the situation.

🏗Consider this an experimental WIP.

### CODE REVIEW

**Comment by regexident** [comment]
Upon further inspection (ie. running https://github.com/MaxDesiatov/XMLCoder/pull/34 repeatedly) the performance seems to have remained stable.

I'd thus propose to merge this PR as it unifies the representation of `T` where `T: Box` and makes it explicit where shared reference semantics is expected.

**Comment by regexident** [comment]
Any chance to have this merged, @MaxDesiatov/@hodovani?

**Comment by MaxDesiatov** [comment]
@regexident I've fixed the conflicts and there's still a `superEncoder` test that fails here. But the most interesting part was that the performance is consistently 10-30% worse, could this be caused by copies of value types? Should we postpone this PR until Swift 5.0 is released or whatever the version is that allows us to improve performance of value types?

screen shot 2019-01-10 at 12 13 14

**Comment by MaxDesiatov** [comment]
All tests are fixed now and since this is a dependency of #55, I'm inclined to merge both of these. After reviewing related issues I'd prefer XMLCoder to be slightly slower, but with #12, #17 and #25 fixed than the opposite 😞

**Comment by regexident** [comment]
Thanks @MaxDesiatov!

**Pull request merged**
