### PR TITLE
Fix Decoding of Nested Arrays of Enums

### LINKED ISSUE #122: Nested enums coding doesn't work
Seems like I found a bug with enums decoding.

Consider the following set of structures describing a book:
```
struct Book: Codable {
    let title: String
    let chapters: [Chapter]
}

enum Chapter {
    struct Content {
        let title: String
        let content: String
    }

    case intro(Content)
    case body(Content)
    case outro(Content)
}
```
and the example xml:
```
let example = """
<?xml version="1.0" encoding="UTF-8"?>
<book title="Example">
    <chapters>
        <intro title="Intro">Content of first chapter</intro>
        <chapter title="Chapter 1">Content of chapter 1</chapter>
        <chapter title="Chapter 2">Content of chapter 2</chapter>
        <outro title="Epilogue">Content of last chapter</outro>
    </chapters>
</book>
"""

let book = try XMLDecoder().decode(Book.self, from: example.data(using: .utf8)!)
```
I'm getting an object with only one chapter `Intro`:
```
Book(title: "Example", 
    chapters: [
        PDF.Chapter.intro(PDF.Chapter.Content(title: "Intro", content: "Content of first chapter"))
    ]
)
```

But if I modify my example like this:
```
let example2 = """
<?xml version="1.0" encoding="UTF-8"?>
<chapters>
    <intro title="Intro">Content of first chapter</intro>
    <chapter title="Chapter 1">Content of chapter 1</chapter>
    <chapter title="Chapter 2">Content of chapter 2</chapter>
    <outro title="Epilogue">Content of last chapter</outro>
</chapters>
"""

let book = try XMLDecoder().decode([Chapter].self, from: example2.data(using: .utf8)!)
```
the result will be a proper array of chapters:
```
[
PDF.Chapter.intro(PDF.Chapter.Content(title: "Intro", content: "Content of first chapter")), 
PDF.Chapter.body(PDF.Chapter.Content(title: "Chapter 1", content: "Content of chapter 1")), 
PDF.Chapter.body(PDF.Chapter.Content(title: "Chapter 2", content: "Content of chapter 2")), 
PDF.Chapter.outro(PDF.Chapter.Content(title: "Epilogue", content: "Content of last chapter"))
]
```

Codable extensions implemented like this:
```
extension Chapter: Codable {
    enum CodingKeys: String, XMLChoiceCodingKey {
        case intro, body = "chapter", outro
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try? container.decode(Content.self, forKey: .body) {
            self = .body(value)
        } else if let value = try? container.decode(Content.self, forKey: .intro) {
            self = .intro(value)
        } else if let value = try? container.decode(Content.self, forKey: .outro) {
            self = .outro(value)
        } else {
            throw BookError.unknownChapterType
        }
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        switch self {
        case .intro(let value):
            try container.encode(value, forKey: .intro)
        case .body(let value):
            try container.encode(value, forKey: .body)
        case .outro(let value):
            try container.encode(value, forKey: .outro)
        }
    }
}

extension Chapter.Content: Codable, DynamicNodeEncoding {
    enum CodingKeys: String, CodingKey {
        case title
        case value = ""
    }

    static func nodeEncoding(for key: CodingKey) -> XMLEncoder.NodeEncoding {
        switch key {
        case CodingKeys.value:
            return .element
        default:
            return .attribute
        }
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        title = try container.decode(String.self, forKey: .title)
        content = try container.decode(String.self, forKey: .value)
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(title, forKey: .title)
        try container.encode(content, forKey: .value)
    }
}
```

Would appreciate any help or suggestion in resolving this issue.

### PR DESCRIPTION
**Pull request by bwetherfield**
I believe the structure in issue #122 provides the right use case for a `nestedUnkeyedContainer` (for key `Chapters`). As such I add a test case with the full proposed usage and a fix for `XMLKeyedDecodingContainer.nestedUnkeyedContainer` on the implementation side that allows the decoding of wrapped arrays of `enum` types.

The key lines on the user-side are within the `Decodable` implementation for `Book`, with decoding initializer using nesting syntax as follows:
```swift
extension Book: Decodable {
    enum CodingKeys: String, CodingKey {
        case title
        case chapters
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        title = try container.decode(String.self, forKey: .title)

        var chapters = [Chapter]()

        if var chapterContainer = try? container.nestedUnkeyedContainer(forKey: .chapters) {
            while !chapterContainer.isAtEnd {
                chapters.append(try chapterContainer.decode(Chapter.self))
            }
        }

        self.chapters = chapters
    }
}
```
`Book` is defined as follows, wrapping an array of the `enum` type `Chapter`.
```swift
struct Book: Decodable {
    let title: String
    let chapters: [Chapter]

    init(title: String, chapters: [Chapter]) {
        self.title = title
        self.chapters = chapters
    }
}
```
More info on how the `enum` type gets decoded from XML choice elements can be found in #119.

### CODE REVIEW

**Comment by bwetherfield** [comment]
@MaxDesiatov, were you able to take a look at this? Thanks!

**Comment by MaxDesiatov** [comment]
@bwetherfield I'm sorry for the delay, it's in my queue now!

**Comment by MaxDesiatov** [comment]
Hi @bwetherfield, I had a quick look and I'm a bit confused by the test case decoding initializer. At a first glance it looks like exactly something that auto-synthesized initializer would do, but if I remove it, the synthesized one decodes only one element. Do you have any thoughts on why that happens? I wonder if achieving the expected behavior with synthesized initializers is possible at all, which would be ideal, wouldn't it?

**Comment by bwetherfield** [comment]
Hi @MaxDesiatov ! From what I understand the `nestedUnkeyedContainer` command only gets called by a user in `Decodable` usage, so I _think_ that would mean that we would need to specify it in a custom initializer. I think that the default initializer does not add any nested structure, which causes the error from #122. My take is that the fix has to be a combination of usage and implementation... Basically I think having the intermediate `<chapters>` nesting is non-standard so the decoder needs to be told what to do (with a call to `nestedUnkeyedContainer`). What do you think?

**Comment by MaxDesiatov** [comment]
Hey @bwetherfield, I again apologize for the delay, August and September turned out to be months with some crazy workload.

It looks like the easiest fix is to add an intermediate `Chapters` struct, with a trivial decoder initializer that calls `singleValueContainer()`, similar to what we did in `NestedChoiceTests`. This doesn't require a more complex initializer that iterates over all of the items in a manually created unkeyed container and doesn't require changes in the library.

I'm going to merge the PR when CI passes, but if there's anything else missing, please feel free to submit new issues/PRs.

**Comment by bwetherfield** [comment]
Nice! That makes a lot of sense. Thanks!

**Pull request merged**
